const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('osuLyrics', {
  initial: () => ipcRenderer.invoke('initial'),
  onState: callback => ipcRenderer.on('state', (_event, data) => callback(data)),
  onLyrics: callback => ipcRenderer.on('lyrics', (_event, data) => callback(data)),
  onTosu: callback => ipcRenderer.on('tosu', (_event, data) => callback(data)),
  onOverlaySettings: callback => ipcRenderer.on('overlay-settings', (_event, data) => callback(data)),
  onOverlayPresence: callback => ipcRenderer.on('overlay-presence', (_event, data) => callback(data)),
  onLayout: callback => ipcRenderer.on('layout', (_event, data) => callback(data)),
  onPanelState: callback => ipcRenderer.on('panel-state', (_event, data) => callback(data)),
  installTosu: () => ipcRenderer.invoke('install-tosu'),
  startTosu: () => ipcRenderer.invoke('start-tosu'),
  searchLyrics: query => ipcRenderer.invoke('search-lyrics', query),
  chooseLyrics: id => ipcRenderer.invoke('choose-lyrics', id),
  offset: delta => ipcRenderer.invoke('offset', delta),
  editLyrics: () => ipcRenderer.invoke('edit-lyrics'),
  importLyrics: () => ipcRenderer.invoke('import-lyrics'),
  windowAction: (action, value) => ipcRenderer.invoke('window-action', action, value),
  panelToggle: open => ipcRenderer.invoke('panel-toggle', open),
  overlayLock: locked => ipcRenderer.invoke('overlay-lock', locked),
  overlayShow: shown => ipcRenderer.invoke('overlay-show', shown),
  updateOverlaySettings: patch => ipcRenderer.invoke('overlay-settings-update', patch),
  overlayVisibility: visible => ipcRenderer.send('overlay-visibility', visible),
  overlayContentHeight: height => ipcRenderer.send('overlay-content-height', height),
  overlayDragStart: pointer => ipcRenderer.invoke('overlay-drag-start', pointer),
  overlayDragMove: pointer => ipcRenderer.send('overlay-drag-move', pointer),
  overlayDragEnd: () => ipcRenderer.send('overlay-drag-end'),
  overlayResizeStart: payload => ipcRenderer.invoke('overlay-resize-start', payload),
  overlayResizeMove: pointer => ipcRenderer.send('overlay-resize-move', pointer),
  overlayResizeEnd: () => ipcRenderer.send('overlay-resize-end'),
});
